# vim keybindings config
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection

# mouse support
setw -g mouse on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# Initialise TMUX plugin manager. TPM is installed by run_once_after_10-install-tpm.sh.
run '~/.tmux/plugins/tpm/tpm'
